### ISSUE TITLE
Account creation - Sign Up button partially covered

### ISSUE THREAD

**Issue by gburchers** [larrylisky/Dashphone#6]
When creating account, after entering email, phone and password, the Sign Up
 button is partially covered by the keyboard and no obvious way to dismiss keyboard.  It is still possible to click the top portion of the accept button

screen shot
<img width="381" alt="Screen Shot 2019-09-20 at 9 54 13 AM" src="https://user-images.githubusercontent.com/19673770/65336885-bf209a00-db8c-11e9-86e4-7cb0a9c3731c.png">

**Comment by larrylisky** [comment]
Fixed in v0.09(13) by elevating the "Sign Up" button.
